export const fixtureData = [
  {
    id: 1,
    datetime: "2024-12-06T02:22:16",
    source: "at facere",
    content: "Et itaque nulla perspiciatis est quo id error qui.",
    topic: "Ante Topić Mimara, Croatian art collector and philanthropist",
    num_followers: 267,
    num_following: 758,
  },
  {
    id: 2,
    datetime: "2024-05-15T03:01:08",
    source: "velit aut",
    content: "Enim nesciunt et quia pariatur et.",
    topic: "Topic, German DJ, producer and musician",
    num_followers: 1000,
    num_following: 1000,
  },
  {
    id: 3,
    datetime: "2024-11-22T09:23:50",
    source: "et esse",
    content: "Suscipit est placeat eos deserunt aut sit.",
    topic: "Ognjen Topic, Serbian-born American Muay Thai kickboxer",
    num_followers: 191,
    num_following: 947,
  },
  {
    id: 4,
    datetime: "2024-02-08T13:51:57",
    source: "sequi et",
    content: "Laborum vitae ad dolores.",
    topic: "Velibor Topić, Bosnian and British actor",
    num_followers: 100,
    num_following: 100,
  },
  {
    id: 5,
    datetime: "2024-05-19T23:56:28",
    source: "quia impedit",
    content: "Maiores dolor amet et quasi.",
    topic: "Mira Topić, Croatian volleyball player",
    num_followers: 842,
    num_following: 124,
  },
];
